version: "3.8"

services:

  chachatte-app:
    depends_on:
      - chachatte-db
    build:
      context: ./
    container_name: chachatte-app
    restart: on-failure
    env_file: ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://chachatte-db:3306/$MARIADB_DATABASE?useUnicode=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=$MARIADB_USER
      - SPRING_DATASOURCE_PASSWORD=$MARIADB_PASSWORD
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - MANAGEMENT_HEALTH_MAIL_ENABLED=false
    networks:
      - chachatte-net
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chachatte.rule=Host(`chachatte.example.com`)"
      - "traefik.http.routers.chachatte.entrypoints=websecure"
      - "traefik.http.routers.chachatte.tls.certresolver=default"
      - "traefik.http.services.chachatte.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-net"

  chachatte-db:
    image: arm64v8/mariadb:latest
    container_name: chachatte-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_AUTO_UPGRADE="1"
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
    volumes:
      - chachatte-db-vol:/var/lib/mysql
    networks:
      - chachatte-net
      - phpmyadmin-net

volumes:

  chachatte-db-vol:
    name: chachatte-db-vol

networks:

  chachatte-net:
    name: chachatte-net

  traefik-net:
    name: traefik-net
    external: true

  phpmyadmin-net:
    name: phpmyadmin-net
    external: true